<?php
define('INDREAMS_DAILY_ARCHVIES', __('Daily Archives', 'indreams'));
define('INDREAMS_MONTHLY_ARCHIVES', __('Monthly Archives', 'indreams'));
define('INDREAMS_YEARLY_ARCHIVES', __('Yearly Archives', 'indreams'));
define('INDREAMS_BLOG_ARCHIVES', __('Blog Archives', 'indreams'));
define('INDREAMS_MOST_USED_CATEGORIES', __('Most Used Categories', 'indreams'));
define('INDREAMS_TRY_LOOKING_MONTHLY_ARCHIVES', __('Try Looking Monthly Archives', 'indreams'));
define('INDREAMS_OLDER_POSTS', __('&larr; Older Posts', 'indreams'));
define('INDREAMS_NEWER_POSTS', __('Newer posts &rarr;', 'indreams'));
define('INDREAMS_RETURN_TO_PREVIUS', __('Return to %s', 'indreams'));
define('INDREAMS_BY_AUTHOR', __('By %2$s', 'indreams'));
define('INDREAMS_VIEW_ALL_POST_BY', __('View all posts by %s', 'indreams'));
define('INDREAMS_PUBLISHED_BY_AUTHOR', __('Published %2$s', 'indreams'));
define('INDREAMS_FULL_SIZE_IS_PIXEL', __('Full size is %s pixels', 'indreams'));
define('INDREAMS_LINK_TO_FULL_SIZE', __('Link to full-size image', 'indreams'));
define('INDREAMS_EDIT', __('Edit', 'indreams'));
define('INDREAMS_BOOKMARK_THE', __('Bookmark the', 'indreams'));
define('INDREAMS_PERMALINK', __('&nbsp;permalink', 'indreams'));
define('INDREAMS_PAGES_COLON', __('Pages:', 'indreams'));
define('INDREAMS_AUTHOR_ARCHIVES', __('Author Archives: %s', 'indreams'));
define('INDREAMS_ABOUT_AUTHOR', __('About %s', 'indreams'));
define('INDREAMS_HOME', __('Home', 'indreams'));
define('INDREAMS_SORRY_NO_POST_MATCHED_YOUR_CRETERIA', __('Sorry no post matched your criteria', 'indreams'));
define('INDREAMS_PRIMARY_WIDGET', __('Primary Widget Area', 'indreams'));
define('INDREAMS_THE_PRIMARY_WIDGET', __('The primary widget area', 'indreams'));
define('INDREAMS_SECONDRY_WIDGET', __('Secondary Widget Area', 'indreams'));
define('INDREAMS_THE_SECONDRY_WIDGET', __('The secondary widget area', 'indreams'));
define('INDREAMS_FIRST_FOOTER_WIDGET', __('First Footer Widget Area', 'indreams'));
define('INDREAMS_THE_FIRST_FOOTER_WIDGET', __('The first footer widget area', 'indreams'));
define('INDREAMS_SECONDRY_FOOTER_WIDGET', __('Second Footer Widget Area', 'indreams'));
define('INDREAMS_THE_SECONDRY_FOOTER_WIDGET', __('The second footer widget area', 'indreams'));
define('INDREAMS_THIRD_FOOTER_WIDGET', __('Third Footer Widget Area', 'indreams'));
define('INDREAMS_THE_THIRD_FOOTER_WIDGET', __('The third footer widget area', 'indreams'));
define('INDREAMS_FOURTH_FOOTER_WIDGET', __('Fourth Footer Widget Area', 'indreams'));
define('INDREAMS_THE_FOURTH_FOOTER_WIDGET', __('The fourth footer widget area', 'indreams'));
define('INDREAMS_MAIN_MENU', __('Main Menu', 'indreams'));
define('INDREAMS_CATEGORIES', __('Categories', 'indreams'));
define('INDREAMS_ARCHIVES', __('Archives', 'indreams'));